### ISSUE TITLE
Whatsapp icon showing only in first post in frontage

### ISSUE THREAD

**Issue by valeriosouza** [valeriosouza/jetpack-whatsapp#10]
I am pretty impressed in this whatsapp plugin and it is working great as expected. My only problem is that, I enabled these to display in front (index) page. But when I am checking in my mobile, it is displaying only in first post. The rest of posts, it is not displaying whatsapp icon. I removed plugin and reinstalled again, but no change. 

https://wordpress.org/support/topic/whatsapp-icon-showing-only-in-first-post-in-frontage

**Comment by heyitsme-milan** [comment]
Same problem, that would be great if the icon will show up for every post on the front page!

**Comment by alpha-rd** [comment]
I can confirm this issue

**Comment by valeriosouza** [comment]
fixed in 1.0.3
